---
- name: Converge
  hosts: all
  tasks:
    - name: "Include create_user"
      include_role:
        name: "create_user"
      vars:
        user_data_directory: /data
        user_name: testuser
        home_directory: /users
        user_password: "testuser"
        user_comment: "This user exists for testing purposes"
        user_shell: /bin/ksh
        user_id: 1500
        main_group:
          name: testusergroup
          gid: 1500
